'use client';
import '@/styles/globals.css'
import { Box, CssBaseline } from "@mui/material";
import Header from "./header/page";
import React, { useState } from 'react'
//import { Inter } from 'next/font/google'
//const inter = Inter({ subsets: ['latin'] })

export let contextData = React.createContext();
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  const [navbarSate, setNavbarState] = useState(false);

  return (
    <html lang="en">
      <body>
        <contextData.Provider value={{ navbarSate, setNavbarState }}>
          <CssBaseline />
          <Header />
          <Box sx={{ position: 'static', 
              bgcolor: '#F4F6F8', 
              minHeight: '100vh', 
              pt: 13,
            }}>
            {children} 
          </Box>
        </contextData.Provider> 
      </body>
    </html>
  )
}
