'use client';
import '@/styles/globals.css';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { Box, CssBaseline } from "@mui/material";
import Header from "./header/page";
import React, { useState } from 'react'
//import { Inter } from 'next/font/google'
//const inter = Inter({ subsets: ['latin'] })

export let sendTheme = React.createContext();
export const metadata = {
  title: 'Developers Job Portal',
  description: 'Generated by create next app',
}

//let theme;

export default function RootLayout({ children }) {

  const [check, setCheck] = useState(false);

  const darkTheme = createTheme({
    palette: {
      mode: `${ check ? 'dark' : 'light' }`,
    },
  });

  //const [navbarSate, setNavbarState] = useState(false);
  /*const toggledTheme = (data) => {
    //'use server';
    //console.log(`This is the data ${data}`);
    return data;
  };
  console.log(toggledTheme())*/

  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={darkTheme}>
          <sendTheme.Provider value={{check, setCheck}}> 
            <CssBaseline />
            <Header />
            <Box sx={{ position: 'static', 
                //bgcolor: `${ checked ? 'black' : '#F4F6F8' }`, 
                minHeight: '100vh', 
                pt: 13,
              }}>
              {children} 
            </Box>
          </sendTheme.Provider>
          
        </ThemeProvider >
      </body>
    </html>
  )
}
